project_id = "xrjwvvemxfzmeogaptzz"

[functions.create-user]
verify_jwt = false

[functions.easyquote-auth]
verify_jwt = false

[functions.easyquote-master-files]
verify_jwt = true

[functions.format-quote-for-pdf]
verify_jwt = true

[functions.easyquote-pricing]
verify_jwt = true

[functions.easyquote-products]
verify_jwt = true

[functions.holded-contacts]
verify_jwt = true

[functions.holded-import-customers]
verify_jwt = true

[functions.save-holded-api-key]
verify_jwt = true

[functions.test-easyquote-connectivity]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.test-product-info]
verify_jwt = true

[functions.delete-holded-customers]
verify_jwt = true

[functions.disable-holded-integration]
verify_jwt = true